services:
  postgres:
    image: postgres:15
    container_name: labflow-postgres
    environment:
      POSTGRES_USER: labflow
      POSTGRES_PASSWORD: labflow
      POSTGRES_DB: labflow
    ports:
      - "5432:5432"
    volumes:
      - labflow-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: labflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  labflow-data:
